# Generated by Django 5.2.5 on 2025-08-21 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100, unique=True)),
                ("url", models.TextField(unique=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField(null=True)),
                ("uploader", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "uploader_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("uploader_url", models.TextField(blank=True, null=True)),
                ("view_count", models.BigIntegerField(null=True)),
                ("like_count", models.BigIntegerField(null=True)),
                ("comment_count", models.BigIntegerField(null=True)),
                ("repost_count", models.BigIntegerField(null=True)),
                ("save_count", models.BigIntegerField(null=True)),
                ("share_count", models.BigIntegerField(null=True)),
                ("upload_date", models.DateField(null=True)),
                ("timestamp", models.BigIntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("fps", models.IntegerField(null=True)),
                ("filesize", models.BigIntegerField(null=True)),
                ("format", models.CharField(blank=True, max_length=50, null=True)),
                ("downloaded_at", models.DateTimeField(null=True)),
                (
                    "downloaded_with",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("platform", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "videos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QueuedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "queued_urls",
                "ordering": ["added_at"],
            },
        ),
    ]
