# Generated by Django 5.2.5 on 2025-08-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_collectorrun_mltrainingrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("whisper_transcription", models.TextField(blank=True, null=True)),
                (
                    "transcription_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("model_used", models.CharField(blank=True, max_length=50, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transcriptions",
                "managed": False,
            },
        ),
    ]
